version: '2'
services:

  console:
    build:
      context: .
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: [${broker1},${broker2},${broker3} ]
          tls:
            enabled: true
            insecureSkipTlsVerify: true
          sasl:
            enabled: true
            username: ${kafka_username}
            mechanism: SCRAM-SHA-512
            password: ${kafka_password}
    ports:
      - "8080:8080"

