version: '2'
services:

  console:
    image: amitca71/redpanda-statefull:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ${KAFKA_BROKERS}
          tls:
            enabled: false
          sasl:
            enabled: false
    ports:
      - "8080:8080"

